// flow-typed signature: 727f914d9d8c00308db6201d5446a7bc
// flow-typed version: <<STUB>>/apidoc-plugin-schema_v^0.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apidoc-plugin-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'apidoc-plugin-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apidoc-plugin-schema/parser/api_schema' {
  declare module.exports: any;
}

declare module 'apidoc-plugin-schema/schema/jsonschema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apidoc-plugin-schema/index' {
  declare module.exports: $Exports<'apidoc-plugin-schema'>;
}
declare module 'apidoc-plugin-schema/index.js' {
  declare module.exports: $Exports<'apidoc-plugin-schema'>;
}
declare module 'apidoc-plugin-schema/parser/api_schema.js' {
  declare module.exports: $Exports<'apidoc-plugin-schema/parser/api_schema'>;
}
declare module 'apidoc-plugin-schema/schema/jsonschema.js' {
  declare module.exports: $Exports<'apidoc-plugin-schema/schema/jsonschema'>;
}
