// flow-typed signature: 249472cf9092304f3eaa4a54b8d7eda2
// flow-typed version: <<STUB>>/common-errors_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'common-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'common-errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'common-errors/lib/alreadyInUse' {
  declare module.exports: any;
}

declare module 'common-errors/lib/argument' {
  declare module.exports: any;
}

declare module 'common-errors/lib/argumentNull' {
  declare module.exports: any;
}

declare module 'common-errors/lib/authenticationRequired' {
  declare module.exports: any;
}

declare module 'common-errors/lib/data/data' {
  declare module.exports: any;
}

declare module 'common-errors/lib/helpers/class-generator' {
  declare module.exports: any;
}

declare module 'common-errors/lib/http-status' {
  declare module.exports: any;
}

declare module 'common-errors/lib/internal/globalize' {
  declare module.exports: any;
}

declare module 'common-errors/lib/invalid-operation' {
  declare module.exports: any;
}

declare module 'common-errors/lib/io/file-load' {
  declare module.exports: any;
}

declare module 'common-errors/lib/io/file-not-found' {
  declare module.exports: any;
}

declare module 'common-errors/lib/io/io' {
  declare module.exports: any;
}

declare module 'common-errors/lib/middleware/crashProtector' {
  declare module.exports: any;
}

declare module 'common-errors/lib/middleware/errorHandler' {
  declare module.exports: any;
}

declare module 'common-errors/lib/not-found' {
  declare module.exports: any;
}

declare module 'common-errors/lib/not-supported' {
  declare module.exports: any;
}

declare module 'common-errors/lib/notPermitted' {
  declare module.exports: any;
}

declare module 'common-errors/lib/timeout' {
  declare module.exports: any;
}

declare module 'common-errors/lib/validation' {
  declare module.exports: any;
}

declare module 'common-errors/tests/already-in-use' {
  declare module.exports: any;
}

declare module 'common-errors/tests/argument-null' {
  declare module.exports: any;
}

declare module 'common-errors/tests/argument' {
  declare module.exports: any;
}

declare module 'common-errors/tests/authentication-required' {
  declare module.exports: any;
}

declare module 'common-errors/tests/connection' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/data' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/memcached' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/mongodb' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/redis' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/rollback' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/sql' {
  declare module.exports: any;
}

declare module 'common-errors/tests/data/transaction' {
  declare module.exports: any;
}

declare module 'common-errors/tests/error' {
  declare module.exports: any;
}

declare module 'common-errors/tests/helpers/class-generator' {
  declare module.exports: any;
}

declare module 'common-errors/tests/helpers/util' {
  declare module.exports: any;
}

declare module 'common-errors/tests/http-status' {
  declare module.exports: any;
}

declare module 'common-errors/tests/invalid-operation' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/directory-not-found' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/drive-not-found' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/end-of-stream' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/file-load' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/file-not-found' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/io' {
  declare module.exports: any;
}

declare module 'common-errors/tests/io/socket' {
  declare module.exports: any;
}

declare module 'common-errors/tests/log' {
  declare module.exports: any;
}

declare module 'common-errors/tests/middleware/errorHandler' {
  declare module.exports: any;
}

declare module 'common-errors/tests/not-found' {
  declare module.exports: any;
}

declare module 'common-errors/tests/not-implemented' {
  declare module.exports: any;
}

declare module 'common-errors/tests/not-permitted' {
  declare module.exports: any;
}

declare module 'common-errors/tests/not-supported' {
  declare module.exports: any;
}

declare module 'common-errors/tests/out-of-memory' {
  declare module.exports: any;
}

declare module 'common-errors/tests/range' {
  declare module.exports: any;
}

declare module 'common-errors/tests/reference' {
  declare module.exports: any;
}

declare module 'common-errors/tests/stack-overflow' {
  declare module.exports: any;
}

declare module 'common-errors/tests/support/index' {
  declare module.exports: any;
}

declare module 'common-errors/tests/syntax' {
  declare module.exports: any;
}

declare module 'common-errors/tests/timeout' {
  declare module.exports: any;
}

declare module 'common-errors/tests/type' {
  declare module.exports: any;
}

declare module 'common-errors/tests/uri' {
  declare module.exports: any;
}

declare module 'common-errors/tests/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'common-errors/index' {
  declare module.exports: $Exports<'common-errors'>;
}
declare module 'common-errors/index.js' {
  declare module.exports: $Exports<'common-errors'>;
}
declare module 'common-errors/lib/alreadyInUse.js' {
  declare module.exports: $Exports<'common-errors/lib/alreadyInUse'>;
}
declare module 'common-errors/lib/argument.js' {
  declare module.exports: $Exports<'common-errors/lib/argument'>;
}
declare module 'common-errors/lib/argumentNull.js' {
  declare module.exports: $Exports<'common-errors/lib/argumentNull'>;
}
declare module 'common-errors/lib/authenticationRequired.js' {
  declare module.exports: $Exports<'common-errors/lib/authenticationRequired'>;
}
declare module 'common-errors/lib/data/data.js' {
  declare module.exports: $Exports<'common-errors/lib/data/data'>;
}
declare module 'common-errors/lib/helpers/class-generator.js' {
  declare module.exports: $Exports<'common-errors/lib/helpers/class-generator'>;
}
declare module 'common-errors/lib/http-status.js' {
  declare module.exports: $Exports<'common-errors/lib/http-status'>;
}
declare module 'common-errors/lib/internal/globalize.js' {
  declare module.exports: $Exports<'common-errors/lib/internal/globalize'>;
}
declare module 'common-errors/lib/invalid-operation.js' {
  declare module.exports: $Exports<'common-errors/lib/invalid-operation'>;
}
declare module 'common-errors/lib/io/file-load.js' {
  declare module.exports: $Exports<'common-errors/lib/io/file-load'>;
}
declare module 'common-errors/lib/io/file-not-found.js' {
  declare module.exports: $Exports<'common-errors/lib/io/file-not-found'>;
}
declare module 'common-errors/lib/io/io.js' {
  declare module.exports: $Exports<'common-errors/lib/io/io'>;
}
declare module 'common-errors/lib/middleware/crashProtector.js' {
  declare module.exports: $Exports<'common-errors/lib/middleware/crashProtector'>;
}
declare module 'common-errors/lib/middleware/errorHandler.js' {
  declare module.exports: $Exports<'common-errors/lib/middleware/errorHandler'>;
}
declare module 'common-errors/lib/not-found.js' {
  declare module.exports: $Exports<'common-errors/lib/not-found'>;
}
declare module 'common-errors/lib/not-supported.js' {
  declare module.exports: $Exports<'common-errors/lib/not-supported'>;
}
declare module 'common-errors/lib/notPermitted.js' {
  declare module.exports: $Exports<'common-errors/lib/notPermitted'>;
}
declare module 'common-errors/lib/timeout.js' {
  declare module.exports: $Exports<'common-errors/lib/timeout'>;
}
declare module 'common-errors/lib/validation.js' {
  declare module.exports: $Exports<'common-errors/lib/validation'>;
}
declare module 'common-errors/tests/already-in-use.js' {
  declare module.exports: $Exports<'common-errors/tests/already-in-use'>;
}
declare module 'common-errors/tests/argument-null.js' {
  declare module.exports: $Exports<'common-errors/tests/argument-null'>;
}
declare module 'common-errors/tests/argument.js' {
  declare module.exports: $Exports<'common-errors/tests/argument'>;
}
declare module 'common-errors/tests/authentication-required.js' {
  declare module.exports: $Exports<'common-errors/tests/authentication-required'>;
}
declare module 'common-errors/tests/connection.js' {
  declare module.exports: $Exports<'common-errors/tests/connection'>;
}
declare module 'common-errors/tests/data/data.js' {
  declare module.exports: $Exports<'common-errors/tests/data/data'>;
}
declare module 'common-errors/tests/data/memcached.js' {
  declare module.exports: $Exports<'common-errors/tests/data/memcached'>;
}
declare module 'common-errors/tests/data/mongodb.js' {
  declare module.exports: $Exports<'common-errors/tests/data/mongodb'>;
}
declare module 'common-errors/tests/data/redis.js' {
  declare module.exports: $Exports<'common-errors/tests/data/redis'>;
}
declare module 'common-errors/tests/data/rollback.js' {
  declare module.exports: $Exports<'common-errors/tests/data/rollback'>;
}
declare module 'common-errors/tests/data/sql.js' {
  declare module.exports: $Exports<'common-errors/tests/data/sql'>;
}
declare module 'common-errors/tests/data/transaction.js' {
  declare module.exports: $Exports<'common-errors/tests/data/transaction'>;
}
declare module 'common-errors/tests/error.js' {
  declare module.exports: $Exports<'common-errors/tests/error'>;
}
declare module 'common-errors/tests/helpers/class-generator.js' {
  declare module.exports: $Exports<'common-errors/tests/helpers/class-generator'>;
}
declare module 'common-errors/tests/helpers/util.js' {
  declare module.exports: $Exports<'common-errors/tests/helpers/util'>;
}
declare module 'common-errors/tests/http-status.js' {
  declare module.exports: $Exports<'common-errors/tests/http-status'>;
}
declare module 'common-errors/tests/invalid-operation.js' {
  declare module.exports: $Exports<'common-errors/tests/invalid-operation'>;
}
declare module 'common-errors/tests/io/directory-not-found.js' {
  declare module.exports: $Exports<'common-errors/tests/io/directory-not-found'>;
}
declare module 'common-errors/tests/io/drive-not-found.js' {
  declare module.exports: $Exports<'common-errors/tests/io/drive-not-found'>;
}
declare module 'common-errors/tests/io/end-of-stream.js' {
  declare module.exports: $Exports<'common-errors/tests/io/end-of-stream'>;
}
declare module 'common-errors/tests/io/file-load.js' {
  declare module.exports: $Exports<'common-errors/tests/io/file-load'>;
}
declare module 'common-errors/tests/io/file-not-found.js' {
  declare module.exports: $Exports<'common-errors/tests/io/file-not-found'>;
}
declare module 'common-errors/tests/io/io.js' {
  declare module.exports: $Exports<'common-errors/tests/io/io'>;
}
declare module 'common-errors/tests/io/socket.js' {
  declare module.exports: $Exports<'common-errors/tests/io/socket'>;
}
declare module 'common-errors/tests/log.js' {
  declare module.exports: $Exports<'common-errors/tests/log'>;
}
declare module 'common-errors/tests/middleware/errorHandler.js' {
  declare module.exports: $Exports<'common-errors/tests/middleware/errorHandler'>;
}
declare module 'common-errors/tests/not-found.js' {
  declare module.exports: $Exports<'common-errors/tests/not-found'>;
}
declare module 'common-errors/tests/not-implemented.js' {
  declare module.exports: $Exports<'common-errors/tests/not-implemented'>;
}
declare module 'common-errors/tests/not-permitted.js' {
  declare module.exports: $Exports<'common-errors/tests/not-permitted'>;
}
declare module 'common-errors/tests/not-supported.js' {
  declare module.exports: $Exports<'common-errors/tests/not-supported'>;
}
declare module 'common-errors/tests/out-of-memory.js' {
  declare module.exports: $Exports<'common-errors/tests/out-of-memory'>;
}
declare module 'common-errors/tests/range.js' {
  declare module.exports: $Exports<'common-errors/tests/range'>;
}
declare module 'common-errors/tests/reference.js' {
  declare module.exports: $Exports<'common-errors/tests/reference'>;
}
declare module 'common-errors/tests/stack-overflow.js' {
  declare module.exports: $Exports<'common-errors/tests/stack-overflow'>;
}
declare module 'common-errors/tests/support/index.js' {
  declare module.exports: $Exports<'common-errors/tests/support/index'>;
}
declare module 'common-errors/tests/syntax.js' {
  declare module.exports: $Exports<'common-errors/tests/syntax'>;
}
declare module 'common-errors/tests/timeout.js' {
  declare module.exports: $Exports<'common-errors/tests/timeout'>;
}
declare module 'common-errors/tests/type.js' {
  declare module.exports: $Exports<'common-errors/tests/type'>;
}
declare module 'common-errors/tests/uri.js' {
  declare module.exports: $Exports<'common-errors/tests/uri'>;
}
declare module 'common-errors/tests/validation.js' {
  declare module.exports: $Exports<'common-errors/tests/validation'>;
}
