// flow-typed signature: f82c48053f9a31e4a3ce3333e3c7d3db
// flow-typed version: <<STUB>>/is_v^3.2.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is/index' {
  declare module.exports: $Exports<'is'>;
}
declare module 'is/index.js' {
  declare module.exports: $Exports<'is'>;
}
declare module 'is/test/index.js' {
  declare module.exports: $Exports<'is/test/index'>;
}
