// flow-typed signature: b2a0afee28cc9c827c291ac1bedb6c33
// flow-typed version: <<STUB>>/latest-version-cli_v^1.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'latest-version-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'latest-version-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'latest-version-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'latest-version-cli/cli.js' {
  declare module.exports: $Exports<'latest-version-cli/cli'>;
}
