// flow-typed signature: c011c00e1861d01fd4712188982bbaab
// flow-typed version: <<STUB>>/ms-amqp-transport_v^7.0.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ms-amqp-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ms-amqp-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ms-amqp-transport/bench/roundtrip' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/examples/consumer' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/amqp' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/defaults' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/index' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/error' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/latency' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/serialization' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/transport' {
  declare module.exports: any;
}

declare module 'ms-amqp-transport/lib/utils/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ms-amqp-transport/bench/roundtrip.js' {
  declare module.exports: $Exports<'ms-amqp-transport/bench/roundtrip'>;
}
declare module 'ms-amqp-transport/examples/consumer.js' {
  declare module.exports: $Exports<'ms-amqp-transport/examples/consumer'>;
}
declare module 'ms-amqp-transport/lib/amqp.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/amqp'>;
}
declare module 'ms-amqp-transport/lib/defaults.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/defaults'>;
}
declare module 'ms-amqp-transport/lib/index.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/index'>;
}
declare module 'ms-amqp-transport/lib/utils/error.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/error'>;
}
declare module 'ms-amqp-transport/lib/utils/latency.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/latency'>;
}
declare module 'ms-amqp-transport/lib/utils/logger.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/logger'>;
}
declare module 'ms-amqp-transport/lib/utils/serialization.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/serialization'>;
}
declare module 'ms-amqp-transport/lib/utils/transport.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/transport'>;
}
declare module 'ms-amqp-transport/lib/utils/validator.js' {
  declare module.exports: $Exports<'ms-amqp-transport/lib/utils/validator'>;
}
