// flow-typed signature: 6dcff1ec8c12990b93a935bfe4b03b63
// flow-typed version: <<STUB>>/ms-conf_v^2.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ms-conf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ms-conf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ms-conf/lib/index' {
  declare module.exports: any;
}

declare module 'ms-conf/lib/load-config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ms-conf/lib/index.js' {
  declare module.exports: $Exports<'ms-conf/lib/index'>;
}
declare module 'ms-conf/lib/load-config.js' {
  declare module.exports: $Exports<'ms-conf/lib/load-config'>;
}
