// flow-typed signature: e70d409a83be17a1a66b74386c4765ca
// flow-typed version: <<STUB>>/ms-validation_v^3.0.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ms-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ms-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ms-validation/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ms-validation/lib/index.js' {
  declare module.exports: $Exports<'ms-validation/lib/index'>;
}
