// flow-typed signature: 76783b965c6334596d8ca12882707f95
// flow-typed version: <<STUB>>/mservice_v^4.7.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mservice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mservice' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mservice/lib/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/amqp' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/amqp/router/adapter' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/cassandra' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/elasticsearch' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/express/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/express/router/adapter' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/express/router/attach' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/hapi/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/hapi/router/adapter' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/hapi/router/attach' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/handlers/restify/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/http/helpers/actionName' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/knex' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/logger' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/redis/migrate' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/redis/utils' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/redisCluster' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/redisSentinel' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/dispatcher' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/extensions/audit/log' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/extensions/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/extensions/index.spec' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/extensions/validate/schemaLessAction' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/factory' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/allowed' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/auth' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/handler' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/lifecycle/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/lifecycle/index.spec' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/request' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/response' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/modules/validate' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/bar' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/baz' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/foo' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/examples/actions/withoutTransport/bar' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/index' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/routes/index.spec' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/router/verifyAttachPossibility' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/socketIO' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/socketIO/router/adapter' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/socketIO/router/attach' {
  declare module.exports: any;
}

declare module 'mservice/lib/plugins/validator' {
  declare module.exports: any;
}

declare module 'mservice/lib/utils/require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mservice/lib/index.js' {
  declare module.exports: $Exports<'mservice/lib/index'>;
}
declare module 'mservice/lib/plugins/amqp.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/amqp'>;
}
declare module 'mservice/lib/plugins/amqp/router/adapter.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/amqp/router/adapter'>;
}
declare module 'mservice/lib/plugins/cassandra.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/cassandra'>;
}
declare module 'mservice/lib/plugins/elasticsearch.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/elasticsearch'>;
}
declare module 'mservice/lib/plugins/http.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http'>;
}
declare module 'mservice/lib/plugins/http/handlers/express/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/express/index'>;
}
declare module 'mservice/lib/plugins/http/handlers/express/router/adapter.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/express/router/adapter'>;
}
declare module 'mservice/lib/plugins/http/handlers/express/router/attach.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/express/router/attach'>;
}
declare module 'mservice/lib/plugins/http/handlers/hapi/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/hapi/index'>;
}
declare module 'mservice/lib/plugins/http/handlers/hapi/router/adapter.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/hapi/router/adapter'>;
}
declare module 'mservice/lib/plugins/http/handlers/hapi/router/attach.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/hapi/router/attach'>;
}
declare module 'mservice/lib/plugins/http/handlers/restify/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/handlers/restify/index'>;
}
declare module 'mservice/lib/plugins/http/helpers/actionName.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/http/helpers/actionName'>;
}
declare module 'mservice/lib/plugins/knex.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/knex'>;
}
declare module 'mservice/lib/plugins/logger.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/logger'>;
}
declare module 'mservice/lib/plugins/redis/migrate.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/redis/migrate'>;
}
declare module 'mservice/lib/plugins/redis/utils.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/redis/utils'>;
}
declare module 'mservice/lib/plugins/redisCluster.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/redisCluster'>;
}
declare module 'mservice/lib/plugins/redisSentinel.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/redisSentinel'>;
}
declare module 'mservice/lib/plugins/router.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router'>;
}
declare module 'mservice/lib/plugins/router/dispatcher.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/dispatcher'>;
}
declare module 'mservice/lib/plugins/router/extensions/audit/log.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/extensions/audit/log'>;
}
declare module 'mservice/lib/plugins/router/extensions/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/extensions/index'>;
}
declare module 'mservice/lib/plugins/router/extensions/index.spec.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/extensions/index.spec'>;
}
declare module 'mservice/lib/plugins/router/extensions/validate/schemaLessAction.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/extensions/validate/schemaLessAction'>;
}
declare module 'mservice/lib/plugins/router/factory.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/factory'>;
}
declare module 'mservice/lib/plugins/router/modules/allowed.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/allowed'>;
}
declare module 'mservice/lib/plugins/router/modules/auth.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/auth'>;
}
declare module 'mservice/lib/plugins/router/modules/handler.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/handler'>;
}
declare module 'mservice/lib/plugins/router/modules/lifecycle/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/lifecycle/index'>;
}
declare module 'mservice/lib/plugins/router/modules/lifecycle/index.spec.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/lifecycle/index.spec'>;
}
declare module 'mservice/lib/plugins/router/modules/request.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/request'>;
}
declare module 'mservice/lib/plugins/router/modules/response.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/response'>;
}
declare module 'mservice/lib/plugins/router/modules/validate.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/modules/validate'>;
}
declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/bar.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/examples/actions/simple/bar'>;
}
declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/baz.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/examples/actions/simple/baz'>;
}
declare module 'mservice/lib/plugins/router/routes/examples/actions/simple/foo.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/examples/actions/simple/foo'>;
}
declare module 'mservice/lib/plugins/router/routes/examples/actions/withoutTransport/bar.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/examples/actions/withoutTransport/bar'>;
}
declare module 'mservice/lib/plugins/router/routes/index.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/index'>;
}
declare module 'mservice/lib/plugins/router/routes/index.spec.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/routes/index.spec'>;
}
declare module 'mservice/lib/plugins/router/verifyAttachPossibility.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/router/verifyAttachPossibility'>;
}
declare module 'mservice/lib/plugins/socketIO.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/socketIO'>;
}
declare module 'mservice/lib/plugins/socketIO/router/adapter.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/socketIO/router/adapter'>;
}
declare module 'mservice/lib/plugins/socketIO/router/attach.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/socketIO/router/attach'>;
}
declare module 'mservice/lib/plugins/validator.js' {
  declare module.exports: $Exports<'mservice/lib/plugins/validator'>;
}
declare module 'mservice/lib/utils/require.js' {
  declare module.exports: $Exports<'mservice/lib/utils/require'>;
}
