// flow-typed signature: 58278484ee60438a82937ad7fdb69553
// flow-typed version: <<STUB>>/pg-native_v^1.10.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-native/bench/index' {
  declare module.exports: any;
}

declare module 'pg-native/bench/leaks' {
  declare module.exports: any;
}

declare module 'pg-native/lib/copy-stream' {
  declare module.exports: any;
}

declare module 'pg-native/test/array-mode' {
  declare module.exports: any;
}

declare module 'pg-native/test/async-workflow' {
  declare module.exports: any;
}

declare module 'pg-native/test/cancel' {
  declare module.exports: any;
}

declare module 'pg-native/test/connection' {
  declare module.exports: any;
}

declare module 'pg-native/test/copy-from' {
  declare module.exports: any;
}

declare module 'pg-native/test/copy-to' {
  declare module.exports: any;
}

declare module 'pg-native/test/custom-types' {
  declare module.exports: any;
}

declare module 'pg-native/test/domains' {
  declare module.exports: any;
}

declare module 'pg-native/test/huge-query' {
  declare module.exports: any;
}

declare module 'pg-native/test/index' {
  declare module.exports: any;
}

declare module 'pg-native/test/load' {
  declare module.exports: any;
}

declare module 'pg-native/test/many-connections' {
  declare module.exports: any;
}

declare module 'pg-native/test/many-errors' {
  declare module.exports: any;
}

declare module 'pg-native/test/multiple-queries' {
  declare module.exports: any;
}

declare module 'pg-native/test/notify' {
  declare module.exports: any;
}

declare module 'pg-native/test/prepare' {
  declare module.exports: any;
}

declare module 'pg-native/test/query-async' {
  declare module.exports: any;
}

declare module 'pg-native/test/query-sync' {
  declare module.exports: any;
}

declare module 'pg-native/test/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-native/bench/index.js' {
  declare module.exports: $Exports<'pg-native/bench/index'>;
}
declare module 'pg-native/bench/leaks.js' {
  declare module.exports: $Exports<'pg-native/bench/leaks'>;
}
declare module 'pg-native/index' {
  declare module.exports: $Exports<'pg-native'>;
}
declare module 'pg-native/index.js' {
  declare module.exports: $Exports<'pg-native'>;
}
declare module 'pg-native/lib/copy-stream.js' {
  declare module.exports: $Exports<'pg-native/lib/copy-stream'>;
}
declare module 'pg-native/test/array-mode.js' {
  declare module.exports: $Exports<'pg-native/test/array-mode'>;
}
declare module 'pg-native/test/async-workflow.js' {
  declare module.exports: $Exports<'pg-native/test/async-workflow'>;
}
declare module 'pg-native/test/cancel.js' {
  declare module.exports: $Exports<'pg-native/test/cancel'>;
}
declare module 'pg-native/test/connection.js' {
  declare module.exports: $Exports<'pg-native/test/connection'>;
}
declare module 'pg-native/test/copy-from.js' {
  declare module.exports: $Exports<'pg-native/test/copy-from'>;
}
declare module 'pg-native/test/copy-to.js' {
  declare module.exports: $Exports<'pg-native/test/copy-to'>;
}
declare module 'pg-native/test/custom-types.js' {
  declare module.exports: $Exports<'pg-native/test/custom-types'>;
}
declare module 'pg-native/test/domains.js' {
  declare module.exports: $Exports<'pg-native/test/domains'>;
}
declare module 'pg-native/test/huge-query.js' {
  declare module.exports: $Exports<'pg-native/test/huge-query'>;
}
declare module 'pg-native/test/index.js' {
  declare module.exports: $Exports<'pg-native/test/index'>;
}
declare module 'pg-native/test/load.js' {
  declare module.exports: $Exports<'pg-native/test/load'>;
}
declare module 'pg-native/test/many-connections.js' {
  declare module.exports: $Exports<'pg-native/test/many-connections'>;
}
declare module 'pg-native/test/many-errors.js' {
  declare module.exports: $Exports<'pg-native/test/many-errors'>;
}
declare module 'pg-native/test/multiple-queries.js' {
  declare module.exports: $Exports<'pg-native/test/multiple-queries'>;
}
declare module 'pg-native/test/notify.js' {
  declare module.exports: $Exports<'pg-native/test/notify'>;
}
declare module 'pg-native/test/prepare.js' {
  declare module.exports: $Exports<'pg-native/test/prepare'>;
}
declare module 'pg-native/test/query-async.js' {
  declare module.exports: $Exports<'pg-native/test/query-async'>;
}
declare module 'pg-native/test/query-sync.js' {
  declare module.exports: $Exports<'pg-native/test/query-sync'>;
}
declare module 'pg-native/test/version.js' {
  declare module.exports: $Exports<'pg-native/test/version'>;
}
