// flow-typed signature: 536aaef816584e2377ea036752390f02
// flow-typed version: <<STUB>>/rrule_v^2.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rrule'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rrule' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rrule/bower_components/timezone-js/spec/date.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/test-utils' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/tz.async.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/tz.default.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/tz.manual.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/tz.preload.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/spec/tz.sync.spec' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/src/date' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/src/node-preparse' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/timezone-js/src/preparse' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/underscore/underscore-min' {
  declare module.exports: any;
}

declare module 'rrule/bower_components/underscore/underscore' {
  declare module.exports: any;
}

declare module 'rrule/lib/nlp' {
  declare module.exports: any;
}

declare module 'rrule/lib/rrule' {
  declare module.exports: any;
}

declare module 'rrule/tests/demo/demo' {
  declare module.exports: any;
}

declare module 'rrule/tests/tests' {
  declare module.exports: any;
}

declare module 'rrule/tests/utils' {
  declare module.exports: any;
}

declare module 'rrule/tests/vendor/jquery' {
  declare module.exports: any;
}

declare module 'rrule/tests/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rrule/bower_components/timezone-js/spec/date.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/date.spec'>;
}
declare module 'rrule/bower_components/timezone-js/spec/test-utils.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/test-utils'>;
}
declare module 'rrule/bower_components/timezone-js/spec/tz.async.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/tz.async.spec'>;
}
declare module 'rrule/bower_components/timezone-js/spec/tz.default.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/tz.default.spec'>;
}
declare module 'rrule/bower_components/timezone-js/spec/tz.manual.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/tz.manual.spec'>;
}
declare module 'rrule/bower_components/timezone-js/spec/tz.preload.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/tz.preload.spec'>;
}
declare module 'rrule/bower_components/timezone-js/spec/tz.sync.spec.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/spec/tz.sync.spec'>;
}
declare module 'rrule/bower_components/timezone-js/src/date.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/src/date'>;
}
declare module 'rrule/bower_components/timezone-js/src/node-preparse.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/src/node-preparse'>;
}
declare module 'rrule/bower_components/timezone-js/src/preparse.js' {
  declare module.exports: $Exports<'rrule/bower_components/timezone-js/src/preparse'>;
}
declare module 'rrule/bower_components/underscore/underscore-min.js' {
  declare module.exports: $Exports<'rrule/bower_components/underscore/underscore-min'>;
}
declare module 'rrule/bower_components/underscore/underscore.js' {
  declare module.exports: $Exports<'rrule/bower_components/underscore/underscore'>;
}
declare module 'rrule/lib/nlp.js' {
  declare module.exports: $Exports<'rrule/lib/nlp'>;
}
declare module 'rrule/lib/rrule.js' {
  declare module.exports: $Exports<'rrule/lib/rrule'>;
}
declare module 'rrule/tests/demo/demo.js' {
  declare module.exports: $Exports<'rrule/tests/demo/demo'>;
}
declare module 'rrule/tests/tests.js' {
  declare module.exports: $Exports<'rrule/tests/tests'>;
}
declare module 'rrule/tests/utils.js' {
  declare module.exports: $Exports<'rrule/tests/utils'>;
}
declare module 'rrule/tests/vendor/jquery.js' {
  declare module.exports: $Exports<'rrule/tests/vendor/jquery'>;
}
declare module 'rrule/tests/vendor/qunit.js' {
  declare module.exports: $Exports<'rrule/tests/vendor/qunit'>;
}
