// flow-typed signature: 45964c2e6865354de8f710f2bb87cdc6
// flow-typed version: <<STUB>>/uid2_v0.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uid2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'uid2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uid2/index' {
  declare module.exports: $Exports<'uid2'>;
}
declare module 'uid2/index.js' {
  declare module.exports: $Exports<'uid2'>;
}
